baseURL = "https://columbia.edu/~js5338"
#relativeURLs = true
languageCode = 'en-us'
title = 'Joe Suk'
theme = 'lugo'
canonifyURLs = true

 # Navigation
[params.navigation]
#other stuff
logo = "logo.png"

# markup stuff needed for html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
